### ISSUE TITLE
Add link to lfx insights site from the contributors page

### ISSUE THREAD

**Issue by arsulegai** [hyperledger-tooling/start-here-hyperledger#273]
Here is a link to the community statistics from Hyperledger https://insights.lfx.linuxfoundation.org/projects/hyperledger-f

**Comment by sahilsuman933** [comment]
Hi @arsulegai , I am Sahil Suman, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you"

**Comment by arsulegai** [comment]
Thanks @sahilsuman933 . Looking forward to it.

**Comment by Swastyy** [comment]
Hi @arsulegai , I want to work on this. Thanks.

**Comment by ChetanDehane** [comment]
Hi @arsulegai , I am Chetan Dehane, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you
